wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.7
    framework: huggingface
    huggingface_version: 4.12.5
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1645413197
    t:
      1:
      - 1
      - 11
      2:
      - 1
      - 11
      3:
      - 16
      4: 3.8.12
      5: 0.12.7
      6: 4.12.5
      8:
      - 5
image size:
  desc: null
  value: 112,112,80
mdoel:
  desc: null
  value: DTC
server:
  desc: null
  value: 57
