wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1644391393
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 16
      4: 3.8.12
      5: 0.12.7
      8:
      - 5
image size:
  desc: null
  value: 112,112,80
mdoel:
  desc: null
  value: DTC
server:
  desc: null
  value: 57
